In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Data/dataset_sample_10k_rows.csv")

C:\Users\Admin\AppData\Local\Temp\ipykernel_3168\3209986515.py:1: DtypeWarning: Columns (13,19,25,52,55,56,57,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,95,96,97,98,99,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,126,127,132,134,135,136,137,138,139,140,152,154,155,156,158,159,160,161,162,164,165,166,167,169,170) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../Data/dataset_sample_10k_rows.csv")

In [3]:
df

,_id,make,model,trim,bodyType,cylinders,year,insureType,chassisNumber,price,...,responseOCRRC.detection.text.registrationCard_202601588_1779793571685-MOI_Vehicle_License_Card.pdf,responseOCRRC.scan.text.registrationCard_202601588_1779793571685-MOI_Vehicle_License_Card.pdf,responseOCRRC.detection.text.registrationCard_202601590_1779800013144-cd984ed3-cfaf-46dd-9ed7-a7b36db903fd.pdf,responseOCRRC.scan.text.registrationCard_202601590_1779800013144-cd984ed3-cfaf-46dd-9ed7-a7b36db903fd.pdf,responseOCRRC.detection.text.registrationCard_202601599_1748279330773-WhatsApp_Image_2025-05-26_at_8.59.47_PM_%281%29.pdf,responseOCRRC.scan.text.registrationCard_202601599_1748279330773-WhatsApp_Image_2025-05-26_at_8.59.47_PM_%281%29.pdf,responseOCRRC.detection.text.registrationCard_202601600_1748278000925-jasper_report_data_viewer.do.pdf,responseOCRRC.scan.text.registrationCard_202601600_1748278000925-jasper_report_data_viewer.do.pdf,responseOCRRC.detection.text.registrationCard_202601596_1748271829747-WhatsApp_Image_2025-05-26_at_3.02.18_PM.pdf,responseOCRRC.scan.text.registrationCard_202601596_1748271829747-WhatsApp_Image_2025-05-26_at_3.02.18_PM.pdf
0,68592fc0f32ddc587c27aafb,TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,thirdparty,JTFHX02P7F0094323,48400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,685935005d8bb5f0ab18a181,TOYOTA,HIACE,DX,Mini Bus High Roof,4.0,2015,thirdparty,JTFHX02P7F0094323,48400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,685944995d8bb5f0ab18bafc,TOYOTA,HILUX,DL,Pick Up Double Cab,4.0,2015,comprehensive,JTFHXDGP7F0094373,37800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,68596237e6bdae3db611dab9,INFINITI,QX50,LUXE STYLE,SUV,4.0,2024,thirdparty,JN1ASNYC3PU200564,142000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,685bb1456ce98addfc08ed19,BMW,420I,M SPORT PREMIUM,COUPE,4.0,2024,thirdparty,WBA11AP04RCR41747,156500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,68dcceb676ce7b9ceab640e5,HYUNDAI,SONATA,GL TOP,SEDAN,4.0,2015,thirdparty,5NPE34AF7FH128187,22400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,68dcceb776ce7b9ceab64122,HONDA,CR-V,LX,SUV,4.0,2015,comprehensive,5J6RM4857FL701428,32600.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,68dccedb76ce7b9ceab64535,NISSAN,PATROL,LE PLATINUM CITY,SUV,8.0,2015,thirdparty,JN8AY2NY6F9139047,107100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,68dccee376ce7b9ceab647a6,NISSAN,KICKS,S,SUV,4.0,2018,thirdparty,3N1CP5C98JL514394,27500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,68dccf4a76ce7b9ceab64e08,NISSAN,PATROL,SE T2,SUV,6.0,2019,thirdparty,JN8BY2NY9K9213740,98900.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.loc[df["make"] == "NISSAN", ["make", "model", "trim", "bodyType", "cylinders", "year", "chassisNumber"]]

,make,model,trim,bodyType,cylinders,year,chassisNumber
22,NISSAN,PATROL,SE TITANIUM,SUV,6.0,2021,JN8BY2NY7M9346550
25,NISSAN,PATROL,SE T1,SUV,8.0,2013,JN8AY2NY7D9069894
26,NISSAN,PATROL,SE T1,SUV,8.0,2013,JN8AY2NY7D9069894
31,NISSAN,PATROL,SE T2,SUV,8.0,2016,JN8AY2NY1G9212861
33,NISSAN,PATHFINDER,CLASSIC XE,SUV,6.0,2014,VSKLR11A7EA547055
...,...,...,...,...,...,...,...
9984,NISSAN,ALTIMA,SV,SEDAN,4.0,2020,1N4BL4BV2LC235203
9994,NISSAN,ALTIMA,SL,SEDAN,4.0,2014,1N4AL3AP9EC152654
9997,NISSAN,PATROL,LE PLATINUM CITY,SUV,8.0,2015,JN8AY2NY6F9139047
9998,NISSAN,KICKS,S,SUV,4.0,2018,3N1CP5C98JL514394
9999,NISSAN,PATROL,SE T2,SUV,6.0,2019,JN8BY2NY9K9213740

In [5]:
df["chassis_attribute"] = df["chassisNumber"].str[3:8]

In [6]:
df["chassis_attribute"]

0       HX02P
1       HX02P
2       HXDGP
3       ASNYC
4       11AP0
        ...
9995    E34AF
9996    RM485
9997    AY2NY
9998    CP5C9
9999    BY2NY
Name: chassis_attribute, Length: 10000, dtype: object

In [7]:
df_nissan = df.loc[df["make"] == "NISSAN", ["make", "model", "trim", "bodyType", "cylinders", "year", "chassisNumber", "chassis_attribute"]]

In [8]:
df_nissan

,make,model,trim,bodyType,cylinders,year,chassisNumber,chassis_attribute
22,NISSAN,PATROL,SE TITANIUM,SUV,6.0,2021,JN8BY2NY7M9346550,BY2NY
25,NISSAN,PATROL,SE T1,SUV,8.0,2013,JN8AY2NY7D9069894,AY2NY
26,NISSAN,PATROL,SE T1,SUV,8.0,2013,JN8AY2NY7D9069894,AY2NY
31,NISSAN,PATROL,SE T2,SUV,8.0,2016,JN8AY2NY1G9212861,AY2NY
33,NISSAN,PATHFINDER,CLASSIC XE,SUV,6.0,2014,VSKLR11A7EA547055,LR11A
...,...,...,...,...,...,...,...,...
9984,NISSAN,ALTIMA,SV,SEDAN,4.0,2020,1N4BL4BV2LC235203,BL4BV
9994,NISSAN,ALTIMA,SL,SEDAN,4.0,2014,1N4AL3AP9EC152654,AL3AP
9997,NISSAN,PATROL,LE PLATINUM CITY,SUV,8.0,2015,JN8AY2NY6F9139047,AY2NY
9998,NISSAN,KICKS,S,SUV,4.0,2018,3N1CP5C98JL514394,CP5C9
9999,NISSAN,PATROL,SE T2,SUV,6.0,2019,JN8BY2NY9K9213740,BY2NY

In [9]:
df_nissan.to_csv("../Data/nissan_data.csv", index=False)