# 🇦🇪 UAE Vehicle Matrix Analysis

This notebook loads, explores, and analyzes the **UAE Vehicle Matrix** dataset containing vehicle models, pricing, technical specifications, and classifications.

### 🛠️ 1. Setup & Imports

To use the `pandas` library (usually abbreviated as `pd`), we must import it first. This cell resolves the `Could not find name pd` error.

In [2]:
import pandas as pd
import numpy as np

print("Pandas imported successfully!")

Pandas imported successfully!

### 📊 2. Load the Dataset

We load the Excel matrix sheet from the `Data/` folder. Since this notebook is located in the `Notebook/` subdirectory, we use a relative path `../Data/uae_vehicle_matrix.xlsx`.

In [3]:
# Load the vehicle matrix excel file
file_path = "../Data/uae_vehicle_matrix.xlsx"
df = pd.read_excel(file_path)

# Display the first 5 rows
df.head()

,Make,Model,Year,Trim,Body Type,Fuel Type,Min Price (AED),Max Price (AED),Avg Price (AED),Engine Size,...,Doors (typical),Seats (typical),Manufactured In,Region Spec,EV Y/N,Chinese Y/N,Classic Y/N,Commercial Y/N,Verified,Unnamed: 22
0,212,T01,2026,Adventure,SUV,Petrol,121275.0,122000.0,121638.0,2.0L,...,4,5,China,GCC,N,N,N,NaN,MSRP,NaN
1,212,T01,2024,Adventurer,SUV,Petrol,109800.0,134200.0,122000.0,2.0L,...,4,5,NaN,GCC,N,N,N,NaN,Marketplace,NaN
2,212,T01,2024,Falcon,SUV,Petrol,148500.0,181500.0,165000.0,2.0L,...,4,5,NaN,GCC,N,N,N,NaN,Marketplace,NaN
3,212,T01,2024,Pioneer,SUV,Petrol,139500.0,170500.0,155000.0,2.0L,...,4,5,NaN,GCC,N,N,N,NaN,Marketplace,NaN
4,AION,AION ES,2024,Standard,Sedan,Electric,76500.0,93500.0,85000.0,NaN,...,4,5,China,GCC,Y,Y,N,NaN,Marketplace,NaN

### 🔍 3. Basic Exploration & Overview

Let's check the size of the dataset, columns, and data types.

In [4]:
print(f"Dataset contains {df.shape[0]} rows and {df.shape[1]} columns.\n")
df.info()

Dataset contains 62811 rows and 23 columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62811 entries, 0 to 62810
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                62811 non-null  object
 1   Model               62811 non-null  object
 2   Year                62811 non-null  int64
 3   Trim                61013 non-null  object
 4   Body Type           62774 non-null  object
 5   Fuel Type           62811 non-null  object
 6   Min Price (AED)     31428 non-null  float64
 7   Max Price (AED)     31428 non-null  float64
 8   Avg Price (AED)     31428 non-null  float64
 9   Engine Size         59421 non-null  object
 10  Cylinders           62811 non-null  int64
 11  Power (HP)          16564 non-null  float64
 12  Ton (PickUps Only)  3208 non-null   float64
 13  Doors (typical)     62811 non-null  int64
 14  Seats (typical)     62811 non-null  int64
 15  Manufactured In     62526 non-null  object
 16  Region Spec         62811 non-null  object
 17  EV Y/N              62811 non-null  object
 18  Chinese Y/N         62811 non-null  object
 19  Classic Y/N         62811 non-null  object
 20  Commercial Y/N      9334 non-null   object
 21  Verified            62811 non-null  object
 22  Unnamed: 22         0 non-null      float64
dtypes: float64(6), int64(4), object(13)
memory usage: 11.0+ MB

### 💰 4. Pricing & Specification Summary

Let's see statistical summaries for the pricing and other continuous columns.

In [5]:
# Statistical summary of the pricing columns
df[['Min Price (AED)', 'Max Price (AED)', 'Avg Price (AED)', 'Power (HP)', 'Engine Size']].describe()

       Min Price (AED)  Max Price (AED)  Avg Price (AED)    Power (HP)
count     3.142800e+04     3.142800e+04     3.142800e+04  16564.000000
mean      2.580263e+05     3.004573e+05     2.792047e+05    282.738227
std       7.353318e+05     8.783999e+05     8.059843e+05    161.334227
min       1.980000e+03     2.420000e+03     2.200000e+03      0.000000
25%       7.879500e+04     9.064000e+04     8.500000e+04    160.000000
50%       1.300000e+05     1.500000e+05     1.400000e+05    246.000000
75%       2.364000e+05     2.640000e+05     2.510000e+05    367.000000
max       2.880000e+07     3.520000e+07     3.200000e+07   2000.000000

### 🔋 5. Electric Vehicles (EVs) Analysis

Let's see the count and proportion of Electric Vehicles in the matrix.

In [6]:
if 'EV Y/N' in df.columns:
    ev_counts = df['EV Y/N'].value_counts(dropna=False)
    print("Electric Vehicle counts:")
    print(ev_counts)
else:
    print("Column 'EV Y/N' not found.")

Electric Vehicle counts:
EV Y/N
N    61098
Y     1713
Name: count, dtype: int64

### 🏢 6. Top Manufacturers

Let's count how many models each manufacturer (`Make`) has in the matrix.

In [7]:
top_makes = df['Make'].value_counts().head(15)
print("Top 15 Manufacturers in the dataset:")
print(top_makes)

Top 15 Manufacturers in the dataset:
Make
Mercedes Benz           5363
BMW                     2984
Toyota                  2861
Ford                    2671
Lexus                   2352
Nissan                  2266
Chevrolet               2155
Mercedes Benz Trucks    2074
Volkswagen              1688
Audi                    1521
Hyundai                 1493
Volvo                   1471
Kia                     1183
Land Rover              1164
Honda                   1107
Name: count, dtype: int64

## Cleaning

In [8]:
df = df.drop(columns=['Unnamed: 22'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62811 entries, 0 to 62810
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                62811 non-null  object
 1   Model               62811 non-null  object
 2   Year                62811 non-null  int64
 3   Trim                61013 non-null  object
 4   Body Type           62774 non-null  object
 5   Fuel Type           62811 non-null  object
 6   Min Price (AED)     31428 non-null  float64
 7   Max Price (AED)     31428 non-null  float64
 8   Avg Price (AED)     31428 non-null  float64
 9   Engine Size         59421 non-null  object
 10  Cylinders           62811 non-null  int64
 11  Power (HP)          16564 non-null  float64
 12  Ton (PickUps Only)  3208 non-null   float64
 13  Doors (typical)     62811 non-null  int64
 14  Seats (typical)     62811 non-null  int64
 15  Manufactured In     62526 non-null  object
 16  Region Spec         62811 non-null  object
 17  EV Y/N              62811 non-null  object
 18  Chinese Y/N         62811 non-null  object
 19  Classic Y/N         62811 non-null  object
 20  Commercial Y/N      9334 non-null   object
 21  Verified            62811 non-null  object
dtypes: float64(5), int64(4), object(13)
memory usage: 10.5+ MB

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df

,Make,Model,Year,Trim,Body Type,Fuel Type,Min Price (AED),Max Price (AED),Avg Price (AED),Engine Size,...,Ton (PickUps Only),Doors (typical),Seats (typical),Manufactured In,Region Spec,EV Y/N,Chinese Y/N,Classic Y/N,Commercial Y/N,Verified
0,212,T01,2026,Adventure,SUV,Petrol,121275.0,122000.0,121638.0,2.0L,...,NaN,4,5,China,GCC,N,N,N,NaN,MSRP
1,212,T01,2024,Adventurer,SUV,Petrol,109800.0,134200.0,122000.0,2.0L,...,NaN,4,5,NaN,GCC,N,N,N,NaN,Marketplace
2,212,T01,2024,Falcon,SUV,Petrol,148500.0,181500.0,165000.0,2.0L,...,NaN,4,5,NaN,GCC,N,N,N,NaN,Marketplace
3,212,T01,2024,Pioneer,SUV,Petrol,139500.0,170500.0,155000.0,2.0L,...,NaN,4,5,NaN,GCC,N,N,N,NaN,Marketplace
4,AION,AION ES,2024,Standard,Sedan,Electric,76500.0,93500.0,85000.0,NaN,...,NaN,4,5,China,GCC,Y,Y,N,NaN,Marketplace
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62806,Zotye,T700,2021,Sport,SUV,Petrol,88065.0,107635.0,97850.0,2.0L,...,NaN,4,5,NaN,GCC,N,N,N,NaN,Marketplace
62807,Zotye,T700,2020,Sport,SUV,Petrol,88065.0,107635.0,97850.0,2.0L,...,NaN,4,5,NaN,GCC,N,N,N,NaN,Marketplace
62808,Zotye,T700,2019,2019 Zotye T700,SUV,Petrol,89900.0,100000.0,94950.0,2.0L,...,NaN,4,5,China,GCC,N,N,N,NaN,MSRP
62809,Zotye,Z100,2016,NaN,Sedan,Petrol,38000.0,50000.0,44000.0,1.0L,...,NaN,4,5,China,GCC,N,N,N,NaN,Web-2026
62810,Zotye,Z100,2015,NaN,Sedan,Petrol,38000.0,50000.0,44000.0,1.0L,...,NaN,4,5,China,GCC,N,N,N,NaN,Web-2026

In [12]:
df.isnull().sum()

Make                      0
Model                     0
Year                      0
Trim                   1798
Body Type                37
Fuel Type                 0
Min Price (AED)       31383
Max Price (AED)       31383
Avg Price (AED)       31383
Engine Size            3390
Cylinders                 0
Power (HP)            46247
Ton (PickUps Only)    59603
Doors (typical)           0
Seats (typical)           0
Manufactured In         285
Region Spec               0
EV Y/N                    0
Chinese Y/N               0
Classic Y/N               0
Commercial Y/N        53477
Verified                  0
dtype: int64

In [13]:
df.value_counts(dropna=False)

Make   Model    Year  Trim        Body Type  Fuel Type  Min Price (AED)  Max Price (AED)  Avg Price (AED)  Engine Size  Cylinders  Power (HP)  Ton (PickUps Only)  Doors (typical)  Seats (typical)  Manufactured In  Region Spec  EV Y/N  Chinese Y/N  Classic Y/N  Commercial Y/N  Verified
212    T01      2024  Adventurer  SUV        Petrol     109800.0         134200.0         122000.0         2.0L         4          NaN         NaN                 4                5                NaN              GCC          N       N            N            NaN             Marketplace    1
                      Falcon      SUV        Petrol     148500.0         181500.0         165000.0         2.0L         4          NaN         NaN                 4                5                NaN              GCC          N       N            N            NaN             Marketplace    1
                      Pioneer     SUV        Petrol     139500.0         170500.0         155000.0         2.0L         4          NaN         NaN                 4                5                NaN              GCC          N       N            N            NaN             Marketplace    1
                2026  Adventure   SUV        Petrol     121275.0         122000.0         121638.0         2.0L         4          248.0       NaN                 4                5                China            GCC          N       N            N            NaN             MSRP           1
AION   AION ES  2024  Standard    Sedan      Electric   76500.0          93500.0          85000.0          NaN          0          NaN         NaN                 4                5                China            GCC          Y       Y            N            NaN             Marketplace    1
                                                                                                                                                                                                                                                                                                   ..
Zotye  T700     2024  Sport       SUV        Petrol     88065.0          107635.0         97850.0          2.0L         4          NaN         NaN                 4                5                NaN              GCC          N       N            N            NaN             Marketplace    1
                2025  Sport       SUV        Petrol     88065.0          107635.0         97850.0          2.0L         4          NaN         NaN                 4                5                NaN              GCC          N       N            N            NaN             Marketplace    1
                2026  Sport       SUV        Petrol     88065.0          107635.0         97850.0          2.0L         4          NaN         NaN                 4                5                NaN              GCC          N       N            N            NaN             Marketplace    1
       Z100     2015  NaN         Sedan      Petrol     38000.0          50000.0          44000.0          1.0L         3          67.0        NaN                 4                5                China            GCC          N       N            N            NaN             Web-2026       1
                2016  NaN         Sedan      Petrol     38000.0          50000.0          44000.0          1.0L         3          67.0        NaN                 4                5                China            GCC          N       N            N            NaN             Web-2026       1
Name: count, Length: 62811, dtype: int64

In [16]:
df["Body Type"].value_counts(dropna=False)

Body Type
SUV                    17725
Sedan                  17708
Truck                   9235
Coupe                   8036
Pickup                  3208
Motorcycle              3191
Van                     2067
Bus                     1389
VAN                      113
Mixer Truck               54
NaN                       37
Backhoe Loader            37
Crawler Tractor            4
Hydraulic Excavator        4
van                        3
Name: count, dtype: int64

In [17]:
df["Engine Size"].value_counts(dropna=False)

Engine Size
2.0L        7353
3.0L        3473
1.6L        3461
NaN         3390
3.5L        3149
            ...
0.25L          1
19.3L          1
5.88L          1
14.8L          1
73.6 kWh       1
Name: count, Length: 185, dtype: int64

In [18]:
df["Trim"].value_counts(dropna=False)

Trim
Standard           6816
NaN                1798
S                   837
Sport               770
SE                  724
                   ...
2015 ZNA Yumsun       1
2016 ZNA Yumsun       1
2011 ZNA Rich         1
2012 ZNA Rich         1
2013 ZNA Rich         1
Name: count, Length: 8696, dtype: int64

In [19]:
df["Year"].value_counts(dropna=False)

Year
2026    3372
2025    3261
2024    3103
2023    3016
2022    2916
2021    2727
2020    2597
2016    2413
2019    2394
2018    2348
2017    2346
2015    2203
2014    2007
2013    1883
2012    1812
2011    1729
2010    1634
2009    1426
2008    1367
2007    1254
2006    1220
2005    1135
2004    1057
2000    1007
2001    1006
2002     990
1999     971
2003     970
1997     965
1998     961
1994     956
1992     956
1996     953
1991     950
1995     949
1993     949
1990     898
2027      67
1987      11
1986       6
1988       6
1985       5
1984       5
1989       4
1982       2
1983       1
1980       1
1974       1
1978       1
Name: count, dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62811 entries, 0 to 62810
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                62811 non-null  object
 1   Model               62811 non-null  object
 2   Year                62811 non-null  int64
 3   Trim                61013 non-null  object
 4   Body Type           62774 non-null  object
 5   Fuel Type           62811 non-null  object
 6   Min Price (AED)     31428 non-null  float64
 7   Max Price (AED)     31428 non-null  float64
 8   Avg Price (AED)     31428 non-null  float64
 9   Engine Size         59421 non-null  object
 10  Cylinders           62811 non-null  int64
 11  Power (HP)          16564 non-null  float64
 12  Ton (PickUps Only)  3208 non-null   float64
 13  Doors (typical)     62811 non-null  int64
 14  Seats (typical)     62811 non-null  int64
 15  Manufactured In     62526 non-null  object
 16  Region Spec         62811 non-null  object
 17  EV Y/N              62811 non-null  object
 18  Chinese Y/N         62811 non-null  object
 19  Classic Y/N         62811 non-null  object
 20  Commercial Y/N      9334 non-null   object
 21  Verified            62811 non-null  object
dtypes: float64(5), int64(4), object(13)
memory usage: 10.5+ MB

In [21]:
df.isnull().sum()

Make                      0
Model                     0
Year                      0
Trim                   1798
Body Type                37
Fuel Type                 0
Min Price (AED)       31383
Max Price (AED)       31383
Avg Price (AED)       31383
Engine Size            3390
Cylinders                 0
Power (HP)            46247
Ton (PickUps Only)    59603
Doors (typical)           0
Seats (typical)           0
Manufactured In         285
Region Spec               0
EV Y/N                    0
Chinese Y/N               0
Classic Y/N               0
Commercial Y/N        53477
Verified                  0
dtype: int64

In [22]:
for col in df.columns:
    print(col)

Make
Model
Year
Trim
Body Type
Fuel Type
Min Price (AED)
Max Price (AED)
Avg Price (AED)
Engine Size
Cylinders
Power (HP)
Ton (PickUps Only)
Doors (typical)
Seats (typical)
Manufactured In
Region Spec
EV Y/N
Chinese Y/N
Classic Y/N
Commercial Y/N
Verified